---
pipeline:
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install -r requirements/ci.txt
      - ./tcp-port-wait.sh postgres 5432
    when:
      event: [pull_request, push, tag]
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=bifrost_api
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DEFAULT_ORG=Humanitec
      - TOLA_TRACK_SYNC_ENABLED=False
      - DEFAULT_FROM_EMAIL=dev@example.com
      - DEFAULT_REPLY_TO=noreply@example.com
      - EMAIL_SUBJECT_PREFIX="[Test]"

  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec/bifrost
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [push, tag]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      event: [push, tag]
      branch: [master]
      status: [failure]

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=bifrost_api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

matrix:
  PYTHON_VERSION:
    - 3.6
