---
pipeline:
  test:
    image: python:${PYTHON_VERSION}-alpine3.7
    commands:
      - apk add --no-cache bash git python-dev gcc musl-dev postgresql-dev libffi-dev libressl-dev
      - pip install -r requirements/ci.txt --no-cache-dir
      - ./tcp-port-wait.sh postgres 5432
      - DJANGO_SETTINGS_MODULE=bifrost-api.settings.base pytest gateway/tests -v --cov  # TODO make all tests run
    when:
      event: [pull_request, push, tag]
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=bifrost_api
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - SECRET_KEY=nothing

  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: registry.tola.io
    repo: registry.tola.io/humanitec-walhall/bifrost
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]

  notify:
    image: plugins/slack
    channel: drone-ci
    username: Drone-CI
    secrets: [SLACK_WEBHOOK]
    when:
      event: [push, tag]
      branch: [master]
      status: [failure]

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=bifrost_api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

matrix:
  PYTHON_VERSION:
    - 3.6
